Update action.yaml

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -28,8 +28,18 @@ runs:
       run: |
         # Download files in parallel using wget
         wget -O tracer-bin https://github.com/fastci-dev/tracer-bin/releases/download/v0.5.8/tracer
+        echo $! > tracer.pid
         chmod +x tracer-bin
       
         # Start tracer
         sudo -E env OTEL_ENDPOINT=${{ inputs.fastci_otel_endpoint }} OTEL_TOKEN=${{ inputs.fastci_otel_token }} ./tracer-bin &
+      shell: bash
+    - name: Stop Fastci Tracer Action
+      if: always()  # Ensure this runs even if the workflow fails
+      run: |
+        if [ -f tracer.pid ]; then
+          kill $(cat tracer.pid) || echo "Tracer process already stopped"
+        else
+          echo "Tracer PID file not found"
+        fi
       shell: bash
